### ISSUE TITLE
Providing Year and Day_of_year values in provided data

### ISSUE THREAD

**Issue by jdeck88** [Phenobase/phenobase_data#3]
Given that i don't have access to the original verbatim dates it would be far easier for data providers to include year and day_of_year themselves to prevent this system for attempting to parse verbatim date values....  This includes @daijiang  provided data...

**Comment by robgur** [comment]
The date field in the sample data file is fine for this - we can give you year and Day of year but I would also like to keep a verbatim data field in the file

**Comment by jdeck88** [comment]
Yeah... having a year and day_of_year added to the file would be great.

**Comment by jdeck88** [comment]
I don't see any argument here... year and day_of_year already added to columns.csv.... closing issue.
