### ISSUE TITLE
model_uri 

### ISSUE THREAD

**Issue by jdeck88** [Phenobase/phenobase_data#5]
We need to populate a field containing a unique identifier for the model that was used.  Suggest a model_uri field.  

robugur said: can we just the one you just created eg https://biscicol.org/api/v1/inaan/ark:/92250/machine_interpreted_model_run_1?  Downstream, we may have metadata about the models we bundle up and can link to this identifier, right?

@jdeck88  said That link above is just an echo of what is contained in the string.  What if we make a [protocols.io](http://protocols.io/) DOI right now?  Russell, maybe this protocol can be made under your account?  Eventually, this protocol will be referenced in a publication and details/further information can be filled out later.   I just made a [protocols.io](http://protocols.io/) account  and a sample protocol in about 5 minutes and got a doi for it.   it takes a bit of time to for the DOI to become "activated" but at least you can get a DOI right away to refer to the model you used and update details later.

@ramonawalls said: I'm okay with this. I just wish it were recorded in a github issue.

In Sum, Russell will be creating a DOI pointing to his model protocol at protocols.io and we'll be using that.

**Comment by rdinnager** [comment]
I think the model should be hosted on HuggingFace (https://huggingface.co/), which allows us to have different model versions, and has been designed for ML models. HuggingFace also allows us to generate a DOI from the model that we can use for the identifier. And we can host the code there as well. Here is an example for a model page: https://huggingface.co/HuggingFaceTB/SmolLM-1.7B . I have an account already and will work on getting the model up there for testing.

**Comment by jdeck88** [comment]
Awesome!  once you get the DOI, please add this to the 300 record test test as our model_uri value.

**Comment by jdeck88** [comment]
Sounds like we agree on the need for using a DOI in model_uri value and @rdinnager is taking care of obtaining that.  this particular issue can be closed.
