### ISSUE TITLE
Change unequivocal/equivocal to certain/uncertain

### ISSUE THREAD

**Issue by robgur** [Phenobase/phenobase_data#6]
From Russell: A bit late to this, but I'm okay with equivocal field being called 'certainty', but I'm not sure I am comfortable calling a model prediction 'certain'. What if the values for certainty were just 'high' and 'low'? Equivocal is low certainty, Unequivocal is high certainty.

I suppose we will also have to change the field 'proportion_equivocal_family' to 'proportion_low_certainty_family', and 'accuracy_excluding_equivocal_family' to 'accuracy_excluding_low_certainty_family'?

**Comment by jdeck88** [comment]
OK, i like the setup where we call the field "certainty" with available values as "low" and "high"  -- that is very clear what we are talking about.

Agreed on "... will also have to change the field 'proportion_equivocal_family' to 'proportion_low_certainty_family', and 'accuracy_excluding_equivocal_family' to 'accuracy_excluding_low_certainty_family'"

Thoughts @robgur ?

**Comment by robgur** [comment]
> OK, i like the setup where we call the field "certainty" with available values as "low" and "high" -- that is very clear what we are talking about.
> 
> Agreed on "... will also have to change the field 'proportion_equivocal_family' to 'proportion_low_certainty_family', and 'accuracy_excluding_equivocal_family' to 'accuracy_excluding_low_certainty_family'"
> 
> Thoughts @robgur ?

I am in agreement on all this.

**Comment by jdeck88** [comment]
Closing issue. columns.csv and certainty.csv files updated with text suggested here in latest commit.
